# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f3e11fa868bd6d4c7bb741d4196f124506e3db11d4e61a93ac15593aed499335aae1ac5c554c084ecd926c47ca117778588b87192665e4b2eb0b70e8b15369

test:
  secret_key_base: d81a2ecf9e1eb189be63cf5cbfd148800cbde0459abbdd40e8d40e668c7a9ba8fa7571c5f4353cff824230c6c140e9471b203755aca055a11e96fdb60790688d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
